export enum EActivityName {
  CREATE_STAGE = 'CREATE_STAGE',
  UPDATE_STAGE = 'UPDATE_STAGE',
  DELETE_STAGE = 'DELETE_STAGE',
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS',
  DELETE_TASK = 'DELETE_TASK',
  CREATE_COMMENT = 'CREATE_COMMENT',
  ADDED_PROJECT = 'ADDED_PROJECT',
  UPDATED_ROLE = 'UPDATED_ROLE',
}
